apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    shared-gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
  labels:
    shared-gateway-access: "true"
  