apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-dev
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      env: dev
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            memory: "2Gi"
            cpu: "0.5"
        ports:
        - containerPort: 80
      nodeSelector:
        env: "dev"
      tolerations:
      - key: env
        operator: Equal
        value: "dev"
        effect: NoSchedule
      